config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :content, presence: true, unless: :image?
end

app/models/user.rb
  class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = current_user.groups.new(group_params)
    @group.users << current_user
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json { @new_messages = @messages.where('id > ?', params[:id])}
       # json形式でアクセスがあった場合は、params[:message][:id]よりも大きいidがないかMessageから検索して、@new_messageに代入する

    end
  end

  #createと、メッセージの非同期通信を行う
  def create
    @message = @group.messages.new(message_params)
      if @message.save
        respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  def show
    @users = Group_users.all(params[:id])
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
    @users = @group.users
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def index
    @users = User.where('name LIKE(?)', "%#{params[:name]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.json
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for(@group) do |f|
  - if @group.errors.any?
    .chat-group-form__errors
      %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバーを追加, class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        = f.text_field :id, value: "", class: 'chat-group-form__input', id: 'user-search-field', placeholder: '追加したいユーザー名を入力してください'
      .user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      .chat-group-users
        .chat-group-user.clearfix
          %p.chat-group-user__name
            = current_user.name

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }
/ .chat-group-form
/   %h1 チャットグループ編集
/   %form#edit_chat_group_22.edit_chat_group{"accept-charset": "UTF-8", action: "/chat_groups/22", method: "post"}
/     %input{name: "utf8", type: "hidden", value: "✓"}/
/     %input{name: "_method", type: "hidden", value: "patch"}/
/     %input{name: "authenticity_token", type: "hidden", value: "U5ABp0/UobRQTSwsR0V40bX1w3t0rZ0CTqrVyLecD+L6sdhBRO/gVcKy7w/Rgxnc7Hf0Ts39996dal3to5fTag=="}/
/     .chat-group-form__field.clearfix
/       .chat-group-form__field--left
/         %label.chat-group-form__label{for: "chat_group_name"} グループ名
/       .chat-group-form__field--right
/         %input#chat_group_name.chat-group-form__input{name: "chat_group[name]", placeholder: "グループ名を入力してください", type: "text", value: "ほげー"}/
/     .chat-group-form__field.clearfix
/       / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
/       /
/         <div class='chat-group-form__field--left'>
/         <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
/         </div>
/         <div class='chat-group-form__field--right'>
/         <div class='chat-group-form__search clearfix'>
/         <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
/         </div>
/         <div id='user-search-result'></div>
/         </div>
/     .chat-group-form__field.clearfix
/       .chat-group-form__field--left
/         %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
/     .chat-group-form__field.clearfix
/       .chat-group-form__field--left
/       .chat-group-form__field--right
/         / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
/         %input.chat-group-form__action-btn{"data-disable-with":"Save", name: "commit", type: "submit", value: "Save"}/

app/views/groups/index.html.haml
.wrapper
  = render "devise/shared/side_bar"
  .chat-main
    .chat-main__header
      .chat-main__header--group
        .chat-main__header--group--name
          TECKEXPERT
        .chat-main__header--group-edit-btn
          = link_to 'EDIT', '#'
        .chat-main__header-members
          MEMBER:araki
    .chat-main__body

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }
/ .chat-group-form
/   %h1 新規チャットグループ
/   = form_for @group do |f|
/     - if @group.errors.any?
/       .chat-group-form__errors
/         %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
/         %ul
/           - @group.errors.full_messages.each do |message|
/             %li= message
/     .chat-group-form__field
/       .chat-group-form__field--left
/         = f.label :name, class: 'chat-group-form__label'
/       .chat-group-form__field--right
/         = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
/     .chat-group-form__field.clearfix
/       / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
/       /
/         <div class='chat-group-form__field--left'>
/         <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
/         </div>
/         <div class='chat-group-form__field--right'>
/         <div class='chat-group-form__search clearfix'>
/         <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
/         </div>
/         <div id='user-search-result'></div>
/         </div>
/     .chat-group-form__field.clearfix
/       .chat-group-form__field--left
/         %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
/       .chat-group-form__field--right
/         = f.collection_check_boxes :user_ids, User.all, :id, :name
/         / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
/         /
/           <div id='chat-group-users'>
/           <div class='chat-group-user clearfix' id='chat-group-user-22'>
/           <input name='chat_group[user_ids][]' type='hidden' value='22'>
/           <p class='chat-group-user__name'>seo_kyohei</p>
/           </div>
/           </div>
/     .chat-group-form__field.clearfix
/       .chat-group-form__field--left
/       .chat-group-form__field--right
/         = f.submit class: 'chat-group-form__action-btn'

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

%body
  = render 'layouts/notifications'
  = yield

app/views/messages/_message.html.haml
.chat-main__body--messages-list{data: {id: "#{message.id}"}}
  .chat-main__message--clearfix
    .chat-main__message--name
      = message.user.name
    .chat-main__message--time
      = message.created_at.to_s(:defalut)
    - if message.content.present?
      .chat-main__message--body
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
.wrapper
  = render "devise/shared/side_bar"
  .chat-main
    .chat-main__header
      .chat-main__header--group
        .chat-main__header--group--name
          = current_user.name
        .chat-main__header--group-edit-btn
          = link_to "EDIT", edit_group_path(@group), class: "chat-main__header--group-edit-btn--name"
        .chat-main__header-members
          MEMBER:
          = @users.pluck(:name).join(",")

    .chat-main__body
      = render @messages
    .chat-main__footer
      = form_for [@group, @message] do |f|
        = f.text_field :content, class: 'form__message', placeholder: 'type a message'
        = f.label :image, class: 'form__mask__image' do
          = fa_icon 'picture-o', class: 'icon'
          = f.file_field :image, class: 'hidden'
        = f.submit 'Send', class: 'form__submit'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'